#!/usr/bin/env python3
"""Sync credentials.json -> secrets.yaml for ESPHome compile/flash.

Usage (from repo root, before esphome run/compile):
    python3 tools/sync_secrets_from_credentials.py

Expected credentials.json:
    {"clientId":"...","clientSecret":"..."}
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "credentials.json"
DST = ROOT / "secrets.yaml"


def yaml_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not SRC.is_file():
        print(f"missing {SRC.name}: put OpenSky clientId/clientSecret there", file=sys.stderr)
        return 1
    data = json.loads(SRC.read_text(encoding="utf-8"))
    cid = (data.get("clientId") or data.get("client_id") or "").strip()
    sec = (data.get("clientSecret") or data.get("client_secret") or "").strip()
    if not cid or not sec:
        print("credentials.json must contain clientId and clientSecret", file=sys.stderr)
        return 1
    DST.write_text(
        "# AUTO-GENERATED by tools/sync_secrets_from_credentials.py — do not commit\n"
        f"opensky_client_id: {yaml_quote(cid)}\n"
        f"opensky_client_secret: {yaml_quote(sec)}\n",
        encoding="utf-8",
    )
    print(f"wrote {DST.relative_to(ROOT)} from {SRC.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
